---
abstract: 'object-oriented gnuplot script builder'
author:
  - 'Toshio Ito <toshioito@cpan.org>'
build_requires:
  Module::Build::Pluggable::CPANfile: '0.05'
  Test::Identity: '0'
  Test::Memory::Cycle: '0'
  Test::More: '0'
configure_requires:
  Module::Build: '0.42'
  Module::Build::Pluggable: '0.09'
  Module::Build::Pluggable::CPANfile: '0.05'
dynamic_config: 1
generated_by: 'Module::Build version 0.4205, CPAN::Meta::Converter version 2.141170'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Gnuplot-Builder
no_index:
  directory:
    - t
    - xt
    - eg
    - inc
  file:
    - README.pod
requires:
  File::Spec: '0'
  IPC::Open3: '0'
  List::Util: '1.28'
  POSIX: '0'
  Scalar::Util: '0'
  Try::Tiny: '0'
  overload: '0'
  parent: '0'
resources:
  bugtracker: https://github.com/debug-ito/Gnuplot-Builder/issues
  repository: git://github.com/debug-ito/Gnuplot-Builder.git
version: '0.21'
